from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

s=Service('C:/Users/79605/Desktop/ТГУ Тестирование ПО/Programms/Python/chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.get("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true")
time.sleep(2)
driver.get("https://qahacking.guru/")
driver.find_element(By.CSS_SELECTOR, ".uk-open:nth-child(1)").click()
driver.find_element(By.CSS_SELECTOR, ".productitem_2 .btn-success").click()
driver.find_element(By.ID, "jshop_attr_id1").click()
    dropdown = self.driver.find_element(By.ID, "jshop_attr_id1")
    dropdown.find_element(By.XPATH, "//option[. = 'Red']").click()
driver.find_element(By.ID, "quantity").click()
driver.find_element(By.ID, "quantity").send_keys("10")
driver.find_element(By.CSS_SELECTOR, ".btn-buy").click()
driver.find_element(By.CSS_SELECTOR, ".cart_reload > img").click()
driver.find_element(By.LINK_TEXT, "Оформить заказ").click()
driver.find_element(By.ID, "f_name").click()
driver.find_element(By.ID, "f_name").send_keys("Дмитрий")
driver.find_element(By.ID, "l_name").send_keys("Тестов")
driver.find_element(By.ID, "email").send_keys("test@test.com")
driver.find_element(By.ID, "street").send_keys("Тестовая ")
driver.find_element(By.ID, "zip").send_keys("215100")
driver.find_element(By.ID, "city").send_keys("Тест")
driver.find_element(By.ID, "state").send_keys("Тестовая")
    dropdown = self.driver.find_element(By.ID, "country")
    dropdown.find_element(By.XPATH, "//option[. = 'Saint Lucia']").click()
    dropdown = self.driver.find_element(By.ID, "country")
    dropdown.find_element(By.XPATH, "//option[. = 'Saint Vincent and the Grenadines']").click()
    dropdown = self.driver.find_element(By.ID, "country")
    dropdown.find_element(By.XPATH, "//option[. = 'Samoa']").click()
driver.find_element(By.ID, "phone").send_keys("9195556677")
driver.find_element(By.NAME, "next").click()
driver.find_element(By.ID, "payment_form").click()
driver.find_element(By.ID, "payment_submit").click()
driver.find_element(By.CSS_SELECTOR, ".button").click()
driver.find_element(By.NAME, "finish_registration").click()
driver.find_element(By.ID, "agb").click()
driver.find_element(By.NAME, "finish_registration").click()
driver.find_element(By.CSS_SELECTOR, ".uk-alert-close > svg").click()
driver.close()
  
